### ISSUE TITLE
屏幕两侧边缘部分无法触发手势和响应任何事件

### ISSUE THREAD

**Issue by bytehub** [xuexiangjys/TemplateSimpleProject#3]
在该模板基础上开发时发现除了主页(MainActivity),其他页面(activity)的边缘部分都无法触发手势和点击事件,即便最简单的布局,两侧大概有10dp左右无法响应事件,试了下xui的demo,也是主页可以,其他activity存在同样问题

**Comment by xuexiangjys** [comment]
那是因为和 SlideBack事件冲突了，你可以禁用 SlideBack

**Comment by jwjlly** [comment]
非常感谢
