### ISSUE TITLE
已找到问题解决方案

### ISSUE THREAD

**Issue by vxinv** [xuexiangjys/TemplateSimpleProject#5]
同样继承BaseFragment 运行之后找不到 Tabbar
无语
@Page(name = "餐桌管理")
public class DefaultFragment extends BaseFragment<FragmentDefaultBinding> implements View.OnClickListener {

    public static final String KEY_TITLE_NAME = "title_name";

    /**
     * 自动注入参数，不能是private
     */
    @AutoWired(name = KEY_TITLE_NAME)
    String title;

    RecyclerView recyclerView;

    @NonNull
    @NotNull
    @Override
    protected FragmentDefaultBinding viewBindingInflate(LayoutInflater inflater, ViewGroup container) {
        return FragmentDefaultBinding.inflate(inflater, container, false);
    }

    @Override
    protected void initViews() {
        //LinearLayoutManager layoutManager = new LinearLayoutManager(getContext());
        /*GridLayoutManager layoutManager = new GridLayoutManager(getContext(), 3);
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        binding.recyclerView.setLayoutManager(layoutManager);
        DeskAdapter deskAdapter = new DeskAdapter(R.layout.fragment_desk, getDeskNet(), this);
        binding.recyclerView.setAdapter(deskAdapter);*/
    }

    @Override
    protected TitleBar initTitle() {
        return null;
    }

    @Override
    protected void initArgs() {
        // 自动注入参数必须在initArgs里进行注入
        XRouter.getInstance().inject(this);
    }

    @Override
    protected String getPageTitle() {
        return title;
    }

    List<DeskEntity> getDeskNet() {
        ArrayList<DeskEntity> desks = new ArrayList<>();
        for (int i = 0; i < 50; i++) {
            DeskEntity deskEntity;
            if (i < 10) {
                deskEntity = new DeskEntity("0" + i, 0);
            } else {
                deskEntity = new DeskEntity("" + i, 0);
            }
            desks.add(deskEntity);
        }
        return desks;
    }

    @Override
    public void onClick(View v) {

    }
}

**Comment by xuexiangjys** [comment]
以你这种狂妄的语气,我建议你还是不要使用这个项目了,我觉得可能不太适合你
