### ISSUE TITLE
aspectj 冲突 META-INF/versions/9/module-info.class 

### ISSUE THREAD

**Issue by Miku06** [xuexiangjys/TemplateSimpleProject#6]
测试了一下应该是第三方包冲突。
implementation 'io.github.lucksiege:pictureselector:v2.7.3-rc08'
猜测应该是这个pictureselector适配了kotlin导致这个报错。

**Comment by xuexiangjys** [comment]
[可参考文档](https://github.com/xuexiangjys/XAOP/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#2%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%AF%8F%E6%AC%A1%E8%BF%90%E8%A1%8C%E7%BC%96%E8%AF%91%E6%97%B6%E4%B8%80%E7%9B%B4%E6%8A%A5%E9%94%99invalid-byte-tag-in-constant-pool%E8%80%8C%E4%B8%94%E4%BC%9A%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E4%B8%80%E4%B8%AAajcorexxxxxxxxxtxt%E6%96%87%E4%BB%B6)
